// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_mservice_control_plane.proto

package mservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("service_mservice_control_plane.proto", fileDescriptor_14cbfd6d5e3fb20b)
}

var fileDescriptor_14cbfd6d5e3fb20b = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0xcf, 0x85, 0x31, 0x92, 0xf3, 0xf3, 0x4a, 0x8a, 0xf2, 0x73, 0xe2, 0x0b,
	0x72, 0x12, 0xf3, 0x52, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60, 0xb2, 0x52, 0xa2,
	0x25, 0x95, 0x05, 0xa9, 0xf1, 0x29, 0x89, 0x25, 0x89, 0xf1, 0xc9, 0x19, 0xa5, 0x79, 0xd9, 0x10,
	0x05, 0x46, 0x7e, 0x5c, 0x22, 0xbe, 0xc1, 0x10, 0x25, 0xce, 0x10, 0xfd, 0x01, 0x20, 0xed, 0x42,
	0x66, 0x5c, 0x2c, 0x2e, 0x89, 0x25, 0x89, 0x42, 0xc2, 0x7a, 0x30, 0x13, 0xf4, 0x40, 0x7c, 0x67,
	0x90, 0x56, 0x29, 0x6c, 0x82, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0x63, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x65, 0x45, 0xea, 0x61, 0x9f, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MServiceControlPlaneClient is the client API for MServiceControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MServiceControlPlaneClient interface {
	// Bi-directional Data stream
	//
	// Some commands can followed by data load. Be it logs, dumps, etc.
	Data(ctx context.Context, opts ...grpc.CallOption) (MServiceControlPlane_DataClient, error)
}

type mServiceControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewMServiceControlPlaneClient(cc grpc.ClientConnInterface) MServiceControlPlaneClient {
	return &mServiceControlPlaneClient{cc}
}

func (c *mServiceControlPlaneClient) Data(ctx context.Context, opts ...grpc.CallOption) (MServiceControlPlane_DataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MServiceControlPlane_serviceDesc.Streams[0], "/mservice.MServiceControlPlane/Data", opts...)
	if err != nil {
		return nil, err
	}
	x := &mServiceControlPlaneDataClient{stream}
	return x, nil
}

type MServiceControlPlane_DataClient interface {
	Send(*DataChunk) error
	Recv() (*DataChunk, error)
	grpc.ClientStream
}

type mServiceControlPlaneDataClient struct {
	grpc.ClientStream
}

func (x *mServiceControlPlaneDataClient) Send(m *DataChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mServiceControlPlaneDataClient) Recv() (*DataChunk, error) {
	m := new(DataChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MServiceControlPlaneServer is the server API for MServiceControlPlane service.
type MServiceControlPlaneServer interface {
	// Bi-directional Data stream
	//
	// Some commands can followed by data load. Be it logs, dumps, etc.
	Data(MServiceControlPlane_DataServer) error
}

// UnimplementedMServiceControlPlaneServer can be embedded to have forward compatible implementations.
type UnimplementedMServiceControlPlaneServer struct {
}

func (*UnimplementedMServiceControlPlaneServer) Data(srv MServiceControlPlane_DataServer) error {
	return status.Errorf(codes.Unimplemented, "method Data not implemented")
}

func RegisterMServiceControlPlaneServer(s *grpc.Server, srv MServiceControlPlaneServer) {
	s.RegisterService(&_MServiceControlPlane_serviceDesc, srv)
}

func _MServiceControlPlane_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MServiceControlPlaneServer).Data(&mServiceControlPlaneDataServer{stream})
}

type MServiceControlPlane_DataServer interface {
	Send(*DataChunk) error
	Recv() (*DataChunk, error)
	grpc.ServerStream
}

type mServiceControlPlaneDataServer struct {
	grpc.ServerStream
}

func (x *mServiceControlPlaneDataServer) Send(m *DataChunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mServiceControlPlaneDataServer) Recv() (*DataChunk, error) {
	m := new(DataChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MServiceControlPlane_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mservice.MServiceControlPlane",
	HandlerType: (*MServiceControlPlaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Data",
			Handler:       _MServiceControlPlane_Data_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service_mservice_control_plane.proto",
}
