// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_metric.proto

package mservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricType int32

const (
	MetricType_METRIC_TYPE_RESERVED    MetricType = 0
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 100
	MetricType_METRIC_TYPE_CPU         MetricType = 200
	MetricType_METRIC_TYPE_RAM         MetricType = 300
)

var MetricType_name = map[int32]string{
	0:   "METRIC_TYPE_RESERVED",
	100: "METRIC_TYPE_UNSPECIFIED",
	200: "METRIC_TYPE_CPU",
	300: "METRIC_TYPE_RAM",
}

var MetricType_value = map[string]int32{
	"METRIC_TYPE_RESERVED":    0,
	"METRIC_TYPE_UNSPECIFIED": 100,
	"METRIC_TYPE_CPU":         200,
	"METRIC_TYPE_RAM":         300,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa4a9edf946d8607, []int{0}
}

type MetricsType int32

const (
	// Due to first enum value has to be zero in proto3
	MetricsType_METRICS_TYPE_RESERVED    MetricsType = 0
	MetricsType_METRICS_TYPE_UNSPECIFIED MetricsType = 100
	// Resource utilization, such as CPU, RAM, etc
	MetricsType_METRICS_TYPE_RESOURCE_UTILIZATION MetricsType = 200
)

var MetricsType_name = map[int32]string{
	0:   "METRICS_TYPE_RESERVED",
	100: "METRICS_TYPE_UNSPECIFIED",
	200: "METRICS_TYPE_RESOURCE_UTILIZATION",
}

var MetricsType_value = map[string]int32{
	"METRICS_TYPE_RESERVED":             0,
	"METRICS_TYPE_UNSPECIFIED":          100,
	"METRICS_TYPE_RESOURCE_UTILIZATION": 200,
}

func (x MetricsType) String() string {
	return proto.EnumName(MetricsType_name, int32(x))
}

func (MetricsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa4a9edf946d8607, []int{1}
}

// Metric is one metric tuple (metric identifier [optional], timestamp [optional], description [optional], metric value)
type Metric struct {
	// Types that are valid to be assigned to TypeOptional:
	//	*Metric_Type
	//	*Metric_Name
	TypeOptional isMetric_TypeOptional `protobuf_oneof:"type_optional"`
	// Types that are valid to be assigned to TimestampOptional:
	//	*Metric_Ts
	TimestampOptional isMetric_TimestampOptional `protobuf_oneof:"timestamp_optional"`
	// Types that are valid to be assigned to DescriptionOptional:
	//	*Metric_Description
	DescriptionOptional isMetric_DescriptionOptional `protobuf_oneof:"description_optional"`
	// Types that are valid to be assigned to Value:
	//	*Metric_StringValue
	//	*Metric_DoubleValue
	//	*Metric_Int32Value
	//	*Metric_Uint32Value
	//	*Metric_Int64Value
	//	*Metric_Uint64Value
	//	*Metric_BytesValue
	Value                isMetric_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4a9edf946d8607, []int{0}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

type isMetric_TypeOptional interface {
	isMetric_TypeOptional()
}

type Metric_Type struct {
	Type MetricType `protobuf:"varint,100,opt,name=type,proto3,enum=mservice.MetricType,oneof"`
}

type Metric_Name struct {
	Name string `protobuf:"bytes,110,opt,name=name,proto3,oneof"`
}

func (*Metric_Type) isMetric_TypeOptional() {}

func (*Metric_Name) isMetric_TypeOptional() {}

func (m *Metric) GetTypeOptional() isMetric_TypeOptional {
	if m != nil {
		return m.TypeOptional
	}
	return nil
}

func (m *Metric) GetType() MetricType {
	if x, ok := m.GetTypeOptional().(*Metric_Type); ok {
		return x.Type
	}
	return MetricType_METRIC_TYPE_RESERVED
}

func (m *Metric) GetName() string {
	if x, ok := m.GetTypeOptional().(*Metric_Name); ok {
		return x.Name
	}
	return ""
}

type isMetric_TimestampOptional interface {
	isMetric_TimestampOptional()
}

type Metric_Ts struct {
	Ts *timestamp.Timestamp `protobuf:"bytes,200,opt,name=ts,proto3,oneof"`
}

func (*Metric_Ts) isMetric_TimestampOptional() {}

func (m *Metric) GetTimestampOptional() isMetric_TimestampOptional {
	if m != nil {
		return m.TimestampOptional
	}
	return nil
}

func (m *Metric) GetTs() *timestamp.Timestamp {
	if x, ok := m.GetTimestampOptional().(*Metric_Ts); ok {
		return x.Ts
	}
	return nil
}

type isMetric_DescriptionOptional interface {
	isMetric_DescriptionOptional()
}

type Metric_Description struct {
	Description string `protobuf:"bytes,300,opt,name=description,proto3,oneof"`
}

func (*Metric_Description) isMetric_DescriptionOptional() {}

func (m *Metric) GetDescriptionOptional() isMetric_DescriptionOptional {
	if m != nil {
		return m.DescriptionOptional
	}
	return nil
}

func (m *Metric) GetDescription() string {
	if x, ok := m.GetDescriptionOptional().(*Metric_Description); ok {
		return x.Description
	}
	return ""
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_StringValue struct {
	StringValue string `protobuf:"bytes,400,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Metric_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,410,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Metric_Int32Value struct {
	Int32Value int32 `protobuf:"varint,420,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Metric_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,430,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Metric_Int64Value struct {
	Int64Value int64 `protobuf:"varint,440,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Metric_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,450,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Metric_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,460,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*Metric_StringValue) isMetric_Value() {}

func (*Metric_DoubleValue) isMetric_Value() {}

func (*Metric_Int32Value) isMetric_Value() {}

func (*Metric_Uint32Value) isMetric_Value() {}

func (*Metric_Int64Value) isMetric_Value() {}

func (*Metric_Uint64Value) isMetric_Value() {}

func (*Metric_BytesValue) isMetric_Value() {}

func (m *Metric) GetValue() isMetric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetStringValue() string {
	if x, ok := m.GetValue().(*Metric_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Metric) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Metric_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Metric) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*Metric_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Metric) GetUint32Value() uint32 {
	if x, ok := m.GetValue().(*Metric_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *Metric) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*Metric_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Metric) GetUint64Value() uint64 {
	if x, ok := m.GetValue().(*Metric_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *Metric) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Metric_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metric_Type)(nil),
		(*Metric_Name)(nil),
		(*Metric_Ts)(nil),
		(*Metric_Description)(nil),
		(*Metric_StringValue)(nil),
		(*Metric_DoubleValue)(nil),
		(*Metric_Int32Value)(nil),
		(*Metric_Uint32Value)(nil),
		(*Metric_Int64Value)(nil),
		(*Metric_Uint64Value)(nil),
		(*Metric_BytesValue)(nil),
	}
}

// Metrics is a set of Metric tuples
type Metrics struct {
	Header *Header `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	// MetricType can be specified once for the whole set of metrics, instead of specifying in each one of them
	MetricType *TypeName `protobuf:"bytes,200,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	// Metrics is the purpose of the whole Metrics data type, is expected to be present all the time
	Metrics              []*Metric `protobuf:"bytes,300,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4a9edf946d8607, []int{1}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Metrics) GetMetricType() *TypeName {
	if m != nil {
		return m.MetricType
	}
	return nil
}

func (m *Metrics) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterEnum("mservice.MetricType", MetricType_name, MetricType_value)
	proto.RegisterEnum("mservice.MetricsType", MetricsType_name, MetricsType_value)
	proto.RegisterType((*Metric)(nil), "mservice.Metric")
	proto.RegisterType((*Metrics)(nil), "mservice.Metrics")
}

func init() {
	proto.RegisterFile("type_metric.proto", fileDescriptor_fa4a9edf946d8607)
}

var fileDescriptor_fa4a9edf946d8607 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0x38, 0x4d, 0x60, 0xdc, 0x52, 0xb3, 0x18, 0x30, 0x01, 0x89, 0x10, 0x10, 0x8a,
	0x82, 0x70, 0xa5, 0x34, 0xea, 0xbd, 0x4d, 0x8d, 0x62, 0x89, 0xa4, 0xd1, 0xc6, 0xa9, 0x04, 0x97,
	0xc8, 0x89, 0x97, 0x60, 0x29, 0xfe, 0x23, 0x7b, 0x5d, 0x29, 0x6f, 0xc1, 0x89, 0x03, 0x67, 0x8e,
	0x15, 0x67, 0xce, 0x9c, 0x72, 0xe0, 0x49, 0x78, 0x0a, 0xb4, 0xbb, 0x76, 0xec, 0xb4, 0x17, 0x4b,
	0xfb, 0xcd, 0x6f, 0xbf, 0x19, 0xed, 0x37, 0x86, 0x87, 0x74, 0x1d, 0x91, 0x99, 0x4f, 0x68, 0xec,
	0x2d, 0x8c, 0x28, 0x0e, 0x69, 0x88, 0xee, 0xf9, 0x09, 0x89, 0xaf, 0xbd, 0x05, 0x69, 0xbc, 0x5c,
	0x86, 0xe1, 0x72, 0x45, 0x8e, 0xb9, 0x3e, 0x4f, 0xbf, 0x1c, 0x53, 0xcf, 0x27, 0x09, 0x75, 0xfc,
	0x48, 0xa0, 0x8d, 0x47, 0xfc, 0x36, 0xfb, 0x04, 0x8e, 0x4f, 0x32, 0x51, 0x58, 0x7e, 0x25, 0x8e,
	0x4b, 0x62, 0x21, 0xb5, 0xfe, 0xc9, 0x50, 0x1b, 0xf2, 0x1e, 0xa8, 0x03, 0x55, 0x56, 0xd7, 0xdd,
	0xa6, 0xd4, 0x7e, 0xd0, 0xd5, 0x8c, 0xbc, 0x99, 0x21, 0xea, 0xf6, 0x3a, 0x22, 0x83, 0x3d, 0xcc,
	0x19, 0xa4, 0x41, 0x95, 0xf9, 0xea, 0x41, 0x53, 0x6a, 0xdf, 0x67, 0x2a, 0x3b, 0xa1, 0xf7, 0x50,
	0xa1, 0x89, 0xbe, 0x91, 0x9a, 0x52, 0x5b, 0xe9, 0x36, 0x0c, 0x31, 0xa3, 0x91, 0xcf, 0x68, 0xd8,
	0xf9, 0x8c, 0x03, 0x09, 0x57, 0x68, 0x82, 0x5e, 0x83, 0xe2, 0x92, 0x64, 0x11, 0x7b, 0x11, 0xf5,
	0xc2, 0x40, 0xbf, 0xa9, 0x70, 0xb3, 0x0a, 0x2e, 0xab, 0xe8, 0x0d, 0x1c, 0x24, 0x34, 0xf6, 0x82,
	0xe5, 0xec, 0xda, 0x59, 0xa5, 0x44, 0xff, 0x26, 0x73, 0x4a, 0xc6, 0x8a, 0x90, 0xaf, 0x98, 0xca,
	0x28, 0x37, 0x4c, 0xe7, 0x2b, 0x92, 0x51, 0x3f, 0x18, 0x25, 0x31, 0x4a, 0xc8, 0x82, 0x6a, 0x81,
	0xe2, 0x05, 0xf4, 0xa4, 0x9b, 0x41, 0x3f, 0x19, 0xb4, 0x3f, 0x90, 0x31, 0x70, 0x75, 0xeb, 0x94,
	0x96, 0xa1, 0x5f, 0x0c, 0x3a, 0x64, 0x4e, 0x69, 0x89, 0x12, 0x4e, 0xa7, 0xbd, 0x0c, 0xfa, 0xcd,
	0x20, 0x39, 0x73, 0x3a, 0xed, 0xed, 0x38, 0x6d, 0xa1, 0x3f, 0x0c, 0xaa, 0xe6, 0x4e, 0x39, 0xd5,
	0x02, 0x65, 0xbe, 0xa6, 0x24, 0xc9, 0xa0, 0xbf, 0x0c, 0x3a, 0x60, 0x4e, 0x5c, 0xe5, 0xcc, 0xf9,
	0x11, 0x1c, 0xf2, 0xe4, 0x42, 0xfe, 0x24, 0xce, 0xea, 0x5c, 0x03, 0xb4, 0x0d, 0xbc, 0x50, 0x9f,
	0x80, 0x56, 0x7a, 0xb9, 0x42, 0xaf, 0xc3, 0x3e, 0x37, 0x6f, 0x7d, 0x97, 0xa0, 0x2e, 0xc2, 0x4c,
	0x50, 0x1b, 0x6a, 0x62, 0x11, 0x78, 0xde, 0x4a, 0x57, 0x2d, 0xf2, 0x1e, 0x70, 0x1d, 0x67, 0x75,
	0xd4, 0x03, 0x45, 0x6c, 0x21, 0x5f, 0xa7, 0x3c, 0x5e, 0x54, 0xf0, 0x6c, 0x33, 0x46, 0x8e, 0x4f,
	0x30, 0xf8, 0xdb, 0x4d, 0x41, 0xef, 0xa0, 0x2e, 0x4e, 0x09, 0x0b, 0x56, 0xde, 0xed, 0x20, 0x86,
	0xc0, 0x39, 0xd1, 0x09, 0x01, 0x8a, 0x25, 0x43, 0x3a, 0x68, 0x43, 0xd3, 0xc6, 0x56, 0x7f, 0x66,
	0x7f, 0x1a, 0x9b, 0x33, 0x6c, 0x4e, 0x4c, 0x7c, 0x65, 0x5e, 0xa8, 0x7b, 0xe8, 0x39, 0x3c, 0x2d,
	0x57, 0xa6, 0xa3, 0xc9, 0xd8, 0xec, 0x5b, 0x1f, 0x2c, 0xf3, 0x42, 0x75, 0x91, 0x06, 0x47, 0xe5,
	0x62, 0x7f, 0x3c, 0x55, 0x37, 0xd2, 0x6d, 0x15, 0x9f, 0x0d, 0xd5, 0x9b, 0x4a, 0x27, 0x00, 0x25,
	0x7b, 0x08, 0xde, 0xf1, 0x19, 0x3c, 0x16, 0xd0, 0xe4, 0x4e, 0xcb, 0x17, 0xa0, 0xef, 0x94, 0x76,
	0x7b, 0xbe, 0x85, 0x57, 0xb7, 0x2f, 0x5e, 0x4e, 0x71, 0xdf, 0x9c, 0x4d, 0x6d, 0xeb, 0xa3, 0xf5,
	0xf9, 0xcc, 0xb6, 0x2e, 0x47, 0xea, 0x46, 0x9a, 0xd7, 0xf8, 0x4f, 0x70, 0xf2, 0x3f, 0x00, 0x00,
	0xff, 0xff, 0x94, 0x81, 0x0f, 0x0d, 0xd5, 0x03, 0x00, 0x00,
}
