// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_metadata.proto

package mservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Metadata describes metadata or the object
type Metadata struct {
	// Types that are valid to be assigned to FilenameOptional:
	//	*Metadata_Filename
	FilenameOptional     isMetadata_FilenameOptional `protobuf_oneof:"filename_optional"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b5234c8ffbbe006, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

type isMetadata_FilenameOptional interface {
	isMetadata_FilenameOptional()
}

type Metadata_Filename struct {
	Filename string `protobuf:"bytes,100,opt,name=filename,proto3,oneof"`
}

func (*Metadata_Filename) isMetadata_FilenameOptional() {}

func (m *Metadata) GetFilenameOptional() isMetadata_FilenameOptional {
	if m != nil {
		return m.FilenameOptional
	}
	return nil
}

func (m *Metadata) GetFilename() string {
	if x, ok := m.GetFilenameOptional().(*Metadata_Filename); ok {
		return x.Filename
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metadata) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metadata_Filename)(nil),
	}
}

func init() {
	proto.RegisterType((*Metadata)(nil), "mservice.Metadata")
}

func init() {
	proto.RegisterFile("type_metadata.proto", fileDescriptor_6b5234c8ffbbe006)
}

var fileDescriptor_6b5234c8ffbbe006 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xa9, 0x2c, 0x48,
	0x8d, 0xcf, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0xc8, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0xb2, 0xe5, 0xe2, 0xf0, 0x85, 0xca,
	0x09, 0xc9, 0x70, 0x71, 0xa4, 0x65, 0xe6, 0xa4, 0xe6, 0x25, 0xe6, 0xa6, 0x4a, 0xa4, 0x28, 0x30,
	0x6a, 0x70, 0x7a, 0x30, 0x04, 0xc1, 0x45, 0x9c, 0x84, 0xb9, 0x04, 0x61, 0xec, 0xf8, 0xfc, 0x82,
	0x92, 0xcc, 0xfc, 0xbc, 0xc4, 0x9c, 0x24, 0x36, 0xb0, 0x79, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x49, 0xe9, 0x59, 0x10, 0x66, 0x00, 0x00, 0x00,
}
